start-mcp-time:
  default:
    rootPath: ./code
    languages:
      - python3.10
    cache:
      paths:
        - "~/.cache"
    steps:
      - run: mkdir -p python
      - run: pip install -r requirements.txt -t ./python
      - run: find ./python/bin -type f -perm -u+x -exec sed -i '1{/^#!.*/ s|.*|#!/usr/bin/env python3|}' {} \;