start-mcp-java-hello-world:
  default:
    languages:
      - java17
    cache:
      paths: 
        - "~/.m2"
    rootPath: ./code
    steps:
      - run: mvn clean install -DskipTests
        path: ./code
    