mcp-server-aliyun-observability:
  default:
    languages:
      - python3.10
    cache:
      paths:
        - "~/.cache"
    steps:
      - run: mkdir -p python
        path: ./code
      - run: pip install -r requirements.txt -t ./python
        path: ./code