start-mcp-server:
  default:
    languages:
      - nodejs20
    cache:
      paths:
        - "~/.npm"
    steps:
      - run: export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true && npm install
        path: ./code
      - run: export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true && npm run build
        path: ./code