name: auto try publish all 

on:
  push:
    branches:
      - main
env:
  REGISTRY_TOKEN:  ${{secrets.ALIBABA_REGISTRY_V3_PUBLISH_TOKEN}} 

jobs:
  auto-publish:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.symlinks false
        shell: bash
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: install s
        run: |
          npm i @serverless-devs/s@3.1.7-9e8d4182 -g
      - name: publish 
        run: |
          python auto-publish.py